# Generated by Django 4.2.7 on 2025-08-08 06:29

from django.db import migrations, models
class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0003_meetup_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image for the meetup', null=True, upload_to='meetups/'),
        ),
        migrations.AddField(
            model_name='meetup',
            name='image_url',
            field=models.URLField(blank=True, help_text='Or provide an image URL', null=True),
        ),
    ]
