# Generated by Django 4.2.7 on 2025-08-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0004_meetup_image_meetup_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='hashtags',
            field=models.TextField(blank=True, help_text='Comma-separated hashtags (e.g., #개발,#네트워킹,#스타트업)', null=True),
        ),
    ]
