# Generated by Django 4.2.23 on 2025-09-06 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0007_add_notification_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetupuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
