# Generated by Django 4.2.7 on 2025-08-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0002_meetup_creator_meetupuser_is_admin_meetupuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
