# Generated by Django 4.2.7 on 2025-08-11 22:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import meetups.models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0005_meetup_hashtags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image for the meetup', null=True, upload_to=meetups.models.meetup_image_path, validators=[meetups.models.validate_image_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])]),
        ),
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waitlisted_at', models.DateTimeField(auto_now_add=True)),
                ('position', models.IntegerField()),
                ('meetup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetups.meetup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetups.meetupuser')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('user', 'meetup')},
            },
        ),
    ]
