# Generated by Django 4.2.23 on 2025-08-15 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0006_alter_meetup_image_waitlist'),
        ('meetups', '0007_add_notification_model'),
    ]

    operations = [
    ]
