# Generated by Django 4.2.23 on 2025-09-06 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0008_alter_meetupuser_email'),
        ('meetups', '0008_merge_20250815_1713'),
    ]

    operations = [
    ]
