# Generated by Django 4.2.7 on 2026-01-22 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0009_merge_20250906_0227'),
        ('meetups', '0009_task_tasksubmission'),
    ]

    operations = [
    ]
