# Generated by Codex on 2026-02-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0011_review_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
