# Generated by Django 4.2.23 on 2026-03-02 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0012_review_created_at_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetupuser',
            name='lightning_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
