# Generated by Django 4.2.23 on 2026-03-02 01:53

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0013_meetupuser_lightning_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetupPaymentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('bolt11', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('meetup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_links', to='meetups.meetup')),
            ],
        ),
    ]
