# Generated by Django 4.2.23 on 2026-06-09 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0014_add_meetup_payment_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetuppaymentlink',
            name='amount_sats',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
