# Generated by Django 4.2.23 on 2026-06-09 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0014_add_meetup_payment_link'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE meetups_meetuppaymentlink ADD COLUMN IF NOT EXISTS amount_sats integer DEFAULT 1 NOT NULL;",
                    reverse_sql="ALTER TABLE meetups_meetuppaymentlink DROP COLUMN IF EXISTS amount_sats;",
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='meetuppaymentlink',
                    name='amount_sats',
                    field=models.PositiveIntegerField(default=1),
                ),
            ],
        ),
    ]
