# Generated by Django 4.2.23 on 2026-06-09 02:33

from django.db import migrations, models


def add_amount_sats(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    with schema_editor.connection.cursor() as cursor:
        if vendor == 'postgresql':
            cursor.execute(
                "ALTER TABLE meetups_meetuppaymentlink ADD COLUMN IF NOT EXISTS amount_sats integer DEFAULT 1 NOT NULL;"
            )
        else:
            cursor.execute("PRAGMA table_info(meetups_meetuppaymentlink);")
            columns = [row[1] for row in cursor.fetchall()]
            if 'amount_sats' not in columns:
                cursor.execute(
                    "ALTER TABLE meetups_meetuppaymentlink ADD COLUMN amount_sats integer DEFAULT 1 NOT NULL;"
                )


def remove_amount_sats(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    with schema_editor.connection.cursor() as cursor:
        if vendor == 'postgresql':
            cursor.execute(
                "ALTER TABLE meetups_meetuppaymentlink DROP COLUMN IF EXISTS amount_sats;"
            )


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0014_add_meetup_payment_link'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_amount_sats, remove_amount_sats),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='meetuppaymentlink',
                    name='amount_sats',
                    field=models.PositiveIntegerField(default=1),
                ),
            ],
        ),
    ]
